namespace osu_request.Websocket;

public enum IncomingOpCode
{
    SOCKET_CONNECTED = 100,

    AUTH_INVALID_USERNAME = 200,
    AUTH_INVALID_CODE = 201,
    AUTH_LOGGED_IN = 202,
    AUTH_ALL_BEATMAPSET_BANS = 203,
    AUTH_ALL_USER_BANS = 204,

    BEATMAPSET_REQUEST = 300,
    BEATMAPSET_BAN = 301,
    BEATMAPSET_UNBAN = 302,

    USER_BAN = 400,
    USER_UNBAN = 401
}

public enum OutgoingOpCode
{
    REQUEST_AUTH = 100,
    REQUEST_BEATMAPSET_BAN = 101,
    REQUEST_BEATMAPSET_UNBAN = 102,
    REQUEST_USER_BAN = 103,
    REQUEST_USER_UNBAN = 104
}